# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Deployment:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
#    - name: Cloning
#      run: git clone https://github.com/hamashoool/rescue-girls.git
    - name: Changing Directory
      run: cd /home/ubuntu/actions-runner/_work/rescue-girls/rescue-girls/rescue-girls && git pull
#    - name: Rerunning The App
#      run: cd /home/ubuntu/actions-runner/rescue_girls_work/rescue-girls/rescue-girls/rescue-girls/rescue_girls_api && sudo docker-compose build --no-cache && sudo docker-compose up -d --force-recreate